create database customer_behaviour_analysis;
use customer_behaviour_analysis;

select * from customer_behaviour_analysis.customer_behavior;

## Q1.What is the total revenue generated by Male vs Female customers ?
select gender,sum(purchase_amount) as total_revenue
from customer_behaviour_analysis.customer_behavior
group by gender;

## Q2.Which customer used a discount but still spent more than average purchase amount?
select customer_id,purchase_amount
from customer_behaviour_analysis.customer_behavior
where discount_applied='Yes' and purchase_amount>
(select avg(purchase_amount) from 
customer_behaviour_analysis.customer_behavior);

## Q3.Which are the top 5 products with the highest average review rating?
select item_purchased,round(avg(Review_Rating),2) as average_rating
from customer_behaviour_analysis.customer_behavior
group by item_purchased
order by avg(Review_Rating) desc
limit 5;

## Q4.Compare average purchase amounts between Standard and Express shipping
select shipping_type,round(avg(purchase_amount),2) as average_purchase_amount
from customer_behaviour_analysis.customer_behavior
where shipping_type in ('Standard','Express')
group by shipping_type
order by avg(purchase_amount) desc;

## Q5.Do subscribed customers spend more?compare average spend and total_revenue beteween subscribers and non subscibers?
select subscription_status,count(*) as customer_count,
round(avg(purchase_amount),2) as average_amount,
round(sum(purchase_amount),2) as total_amount
from customer_behaviour_analysis.customer_behavior
group by subscription_status
order by total_amount,average_amount desc;

## Q6.Which top 5 products have the highest percentage of purchase with discount applied?
select item_purchased,
round(sum(case when discount_applied='Yes' then 1 else 0 end)/count(*) * 100,2) as discount_rate
from customer_behaviour_analysis.customer_behavior
group by item_purchased
order by discount_rate desc
limit 5;

#Q7. segment customers into New,Returning, and Loyal based on their total?
with customer_segment as (
select customer_id,previous_purchases,
case
when previous_purchases=1 then 'New Customer'
when previous_purchases between 2 and 10 then 'Returning Customer'
else 'Loyal Customer' end as segment
from customer_behaviour_analysis.customer_behavior
)
select segment,count(*) as count_of_customer
from customer_segment
group by segment;


# Q8.Top 3 selling products within each category
with product_rank as (select category,item_purchased,count(*) as count_of_products,
row_number() over (partition by category order by count(*) desc) as ranking
from customer_behaviour_analysis.customer_behavior
group by category,item_purchased)

select ranking,category,item_purchased,count_of_products
from product_rank
where ranking<=3;


# Q9.Are customers who are repeated customers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(*) as count_of_customer
from customer_behaviour_analysis.customer_behavior
where previous_purchases>5
group by subscription_status;

# Q10.Revenue cntribution of each age segment
select age_group,sum(purchase_amount) as total_amount
from customer_behaviour_analysis.customer_behavior
group by age_group
order by total_amount desc;